// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"zocket-task/pkg/api"
	"zocket-task/pkg/api/handlers"
	"zocket-task/pkg/config"
	"zocket-task/pkg/controller"
	"zocket-task/pkg/datalayer"
	"zocket-task/pkg/dbconnection"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.ServerHTTP, error) {
	db, err := dbconnection.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	authDataLayer := datalayer.NewUserAuthenticationDL(db)
	authController := controller.NewAuthController(authDataLayer)
	authHandler := handlers.NewAuthHandler(authController)
	serverHTTP := api.NewServerHTTP(authHandler)
	return serverHTTP, nil
}
